### ISSUE TITLE
docker version?

### ISSUE THREAD

**Issue by davidmoshal** [WhiteLord/sonar-jenkins#8]
Hi, I reviewed your codebase prior to buying your course on Udemy.

However, I was turned off because it looks like I'm going to have to manually install of the software on my Ubuntu desktop machine, or in a virtual box and then subsequently figure out how to make this work with a docker compose file.  

The course would be way more attractive if you provided a docker-compose file and used containers for the various components (Jenkins, Postgres, SonarQube, etc).

Just my 2 cents.

**Comment by WhiteLord** [comment]
Thanks for the update!
Yes, that's nice to have. Back in the day when I made the series I haven't put much thought in this.

This will be something I will include in the series in the coming weeks.

**Comment by WhiteLord** [comment]
[Continuous code inspection with SonarQube](https://www.udemy.com/course/continuous-code-inspection-with-sonarqube/) now includes a docker-compose file with a separate network, volumes for the containers, and a custom docker image available in one of my repositories [on GitHub](https://github.com/WhiteLord/docker-jenkins) or on [DockerHub](https://hub.docker.com/r/georgespasov/docker-jenkins)
